import os

class Config:
    MYSQL_DATABASE_USER = 'root'
    MYSQL_DATABASE_PASSWORD = '1027150930Juan*'
    MYSQL_DATABASE_DB = 'heladeria'
    MYSQL_DATABASE_HOST = 'localhost'
    SQLALCHEMY_DATABASE_URI = f"mysql://{MYSQL_DATABASE_USER}:{MYSQL_DATABASE_PASSWORD}@{MYSQL_DATABASE_HOST}/{MYSQL_DATABASE_DB}"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.urandom(24)
